packages:
    - "packages/core"
    - "packages/adapter-sqlite"
    - "packages/client-direct"
    - "agent"
exclude:
    - "**/client-discord"
    - "**/plugin-*"
    - "**/adapter-postgres"
    - "**/adapter-supabase"
    - "**/adapter-sqljs"
